# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FemtoTrader's site
email: femto.trader@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Geek (or nerd?), physicist (academic position) and 
  amateur trader (trying to become a much more professional investor ;-) )
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://femtotrader.github.io" # the base hostname & protocol for your site
twitter_username: FemtoTrader
github_username:  femtotrader
linked_url: https://goo.gl/sAe46D

# Build settings
markdown: kramdown
